name: ElectricSpawners
version: ${project.version}
author: TheBusyBiscuit
depend: [Slimefun]
softdepend: [GuizhanLibPlugin]

api-version: 1.13

main: io.github.thebusybiscuit.electricspawners.ElectricSpawners